# Generated by Django 5.0.3 on 2024-05-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Necessiteux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('degre_urgence', models.CharField(choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Élevé', 'Élevé')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En attente', max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='besoins/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='besoins/documents/')),
                ('video', models.FileField(blank=True, null=True, upload_to='besoins/videos/')),
                ('necessiteux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Necessiteux.necessiteux')),
            ],
            options={
                'verbose_name': 'Besoin',
                'verbose_name_plural': 'Besoins ',
                'db_table': 'besoin',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BesoinDeBenevoles',
            fields=[
                ('besoin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website_part.besoin')),
                ('duree', models.CharField(max_length=100)),
                ('nombre_de_benevoles', models.PositiveIntegerField()),
                ('competences_demandees', models.TextField()),
            ],
            options={
                'verbose_name': 'Besoin de bénévoles',
                'verbose_name_plural': 'Besoins de bénévoles',
                'db_table': 'besoin_de_benevoles',
            },
            bases=('website_part.besoin',),
        ),
        migrations.CreateModel(
            name='BesoinFinancier',
            fields=[
                ('besoin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website_part.besoin')),
                ('montant_souhaite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_collecte', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Besoin Financier',
                'verbose_name_plural': 'Besoins Financiers',
                'db_table': 'besoin_financier',
            },
            bases=('website_part.besoin',),
        ),
        migrations.CreateModel(
            name='BesoinMateriel',
            fields=[
                ('besoin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website_part.besoin')),
                ('categorie', models.CharField(choices=[('Nourriture', 'Nourriture'), ('Vêtements', 'Vêtements'), ('Logement', 'Logement'), ('Éducation', 'Éducation')], max_length=50)),
                ('quantite', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Besoin Matériel',
                'verbose_name_plural': 'Besoins Matériels',
                'db_table': 'besoin_materiel',
            },
            bases=('website_part.besoin',),
        ),
    ]
