# Generated by Django 5.0.4 on 2024-05-29 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('degre_urgence', models.CharField(choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Élevé', 'Élevé')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En attente', max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='besoins/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='besoins/documents/')),
                ('video', models.FileField(blank=True, null=True, upload_to='besoins/videos/')),
            ],
            options={
                'verbose_name': 'Besoin',
                'verbose_name_plural': 'Besoins ',
                'db_table': 'besoin',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Necessiteux',
            fields=[
                ('utilisateurpersonnalise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type_necessiteux', models.CharField(choices=[('personne', 'Personne'), ('organisation', 'Organisation')], max_length=100)),
            ],
            options={
                'verbose_name': 'Nécessiteux',
                'verbose_name_plural': 'Nécessiteux',
                'db_table': 'necessiteux',
            },
            bases=('comptes.utilisateurpersonnalise',),
        ),
        migrations.CreateModel(
            name='BesoinDeBenevoles',
            fields=[
                ('besoin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Necessiteux.besoin')),
                ('duree', models.CharField(max_length=100)),
                ('nombre_de_benevoles', models.PositiveIntegerField()),
                ('competences_demandees', models.TextField()),
            ],
            options={
                'verbose_name': 'Besoin de bénévoles',
                'verbose_name_plural': 'Besoins de bénévoles',
                'db_table': 'besoin_de_benevoles',
            },
            bases=('Necessiteux.besoin',),
        ),
        migrations.CreateModel(
            name='BesoinFinancier',
            fields=[
                ('besoin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Necessiteux.besoin')),
                ('montant_souhaite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_collecte', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Besoin Financier',
                'verbose_name_plural': 'Besoins Financiers',
                'db_table': 'besoin_financier',
            },
            bases=('Necessiteux.besoin',),
        ),
        migrations.CreateModel(
            name='BesoinMateriel',
            fields=[
                ('besoin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Necessiteux.besoin')),
                ('categorie', models.CharField(choices=[('Nourriture', 'Nourriture'), ('Vêtements', 'Vêtements'), ('Logement', 'Logement'), ('Éducation', 'Éducation')], max_length=50)),
                ('quantite', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Besoin Matériel',
                'verbose_name_plural': 'Besoins Matériels',
                'db_table': 'besoin_materiel',
            },
            bases=('Necessiteux.besoin',),
        ),
        migrations.CreateModel(
            name='NecessiteuxOrganisation',
            fields=[
                ('necessiteux_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Necessiteux.necessiteux')),
                ('numero_matd', models.CharField(max_length=100, unique=True)),
                ('agrement_maspfe', models.CharField(max_length=100, unique=True)),
                ('statut_juridique', models.CharField(choices=[('EI', 'Entreprise Individuelle'), ('EIRL', 'Entreprise Individuelle a Responsabilité Limitée'), ('SARL', 'Societé à Responsabilité Limitée'), ('EURL', ' Entreprise Unipersonnelle à Responsabilité Limitée'), ('EURL', 'Société par Actions Simplifiée'), ('SA', 'Société Anonyme')], max_length=100)),
                ('date_creation', models.DateField()),
            ],
            options={
                'verbose_name': 'Nécessiteux Organisation',
                'verbose_name_plural': 'Nécessiteux Organisations',
                'db_table': 'necessiteux_organisation',
            },
            bases=('Necessiteux.necessiteux',),
        ),
        migrations.CreateModel(
            name='NecessiteuxPersonne',
            fields=[
                ('necessiteux_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Necessiteux.necessiteux')),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10)),
                ('date_naissance', models.DateField()),
            ],
            options={
                'verbose_name': 'Nécessiteux Personne',
                'verbose_name_plural': 'Nécessiteux Personnes',
                'db_table': 'necessiteux_personne',
            },
            bases=('Necessiteux.necessiteux',),
        ),
        migrations.AddField(
            model_name='besoin',
            name='necessiteux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Necessiteux.necessiteux'),
        ),
    ]
