# Generated by Django 5.0.3 on 2024-05-23 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Necessiteux',
            fields=[
                ('utilisateurpersonnalise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type_necessiteux', models.CharField(choices=[('personne', 'Personne'), ('organisation', 'Organisation')], max_length=100)),
            ],
            options={
                'verbose_name': 'Nécessiteux',
                'verbose_name_plural': 'Nécessiteux',
                'db_table': 'necessiteux',
            },
            bases=('comptes.utilisateurpersonnalise',),
        ),
        migrations.CreateModel(
            name='NecessiteuxOrganisation',
            fields=[
                ('necessiteux_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Necessiteux.necessiteux')),
                ('numero_matd', models.CharField(max_length=100, unique=True)),
                ('agrement_maspfe', models.CharField(max_length=100, unique=True)),
                ('statut_juridique', models.CharField(choices=[('EI', 'Entreprise Individuelle'), ('EIRL', 'Entreprise Individuelle a Responsabilité Limitée'), ('SARL', 'Societé à Responsabilité Limitée'), ('EURL', ' Entreprise Unipersonnelle à Responsabilité Limitée'), ('EURL', 'Société par Actions Simplifiée'), ('SA', 'Société Anonyme')], max_length=100)),
                ('date_creation', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Nécessiteux Organisation',
                'verbose_name_plural': 'Nécessiteux Organisations',
                'db_table': 'necessiteux_organisation',
            },
            bases=('Necessiteux.necessiteux',),
        ),
        migrations.CreateModel(
            name='NecessiteuxPersonne',
            fields=[
                ('necessiteux_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Necessiteux.necessiteux')),
                ('prenom', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10)),
                ('date_naissance', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Nécessiteux Personne',
                'verbose_name_plural': 'Nécessiteux Personnes',
                'db_table': 'necessiteux_personne',
            },
            bases=('Necessiteux.necessiteux',),
        ),
    ]
