# Generated by Django 5.0.3 on 2024-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Necessiteux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessiteuxorganisation',
            name='date_creation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='necessiteuxpersonne',
            name='date_naissance',
            field=models.DateTimeField(),
        ),
    ]
