# Generated by Django 5.0.4 on 2024-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Necessiteux', '0002_alter_necessiteuxorganisation_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessiteuxorganisation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='necessiteuxorganisation',
            name='type_necessiteux',
            field=models.CharField(choices=[('personne', 'Personne'), ('organisation', 'Organisation')], max_length=100),
        ),
        migrations.AlterField(
            model_name='necessiteuxpersonne',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='necessiteuxpersonne',
            name='type_necessiteux',
            field=models.CharField(choices=[('personne', 'Personne'), ('organisation', 'Organisation')], max_length=100),
        ),
    ]
