# Generated by Django 5.0.4 on 2024-05-17 17:13

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Necessiteux', '0003_alter_necessiteuxorganisation_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessiteuxorganisation',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='necessiteuxpersonne',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
