# Generated by Django 5.0.3 on 2024-05-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_donateur', models.CharField(choices=[('individu', 'Individu'), ('entreprise', 'Entreprise'), ('organisation', 'Organisation')], max_length=100)),
                ('preferences_besoins', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=100)),
                ('numero_fiscal', models.CharField(max_length=100)),
                ('statut_juridique', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.utilisateurpersonnalise')),
            ],
            options={
                'verbose_name': 'Donateur Entreprise',
                'verbose_name_plural': 'Donateurs Entreprise',
            },
        ),
        migrations.CreateModel(
            name='DonateurOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_donateur', models.CharField(choices=[('individu', 'Individu'), ('entreprise', 'Entreprise'), ('organisation', 'Organisation')], max_length=100)),
                ('preferences_besoins', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=100)),
                ('numero_MATD', models.CharField(max_length=100)),
                ('statut_juridique', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.utilisateurpersonnalise')),
            ],
            options={
                'verbose_name': 'Donateur Organisation',
                'verbose_name_plural': 'Donateurs Organisation',
            },
        ),
        migrations.CreateModel(
            name='DonateurPersonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_donateur', models.CharField(choices=[('individu', 'Individu'), ('entreprise', 'Entreprise'), ('organisation', 'Organisation')], max_length=100)),
                ('preferences_besoins', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.utilisateurpersonnalise')),
            ],
            options={
                'verbose_name': 'Donateur Personne',
                'verbose_name_plural': 'Donateurs Personnes',
            },
        ),
    ]
