# Generated by Django 5.0.4 on 2024-05-29 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donateur',
            fields=[
                ('utilisateurpersonnalise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type_donateur', models.CharField(choices=[('personne', 'Personne'), ('entreprise', 'Entreprise'), ('organisation', 'Organisation')], max_length=100)),
                ('preferences_besoins', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_donateur', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Donateur',
                'verbose_name_plural': 'Donateurs',
                'db_table': 'donateur',
            },
            bases=('comptes.utilisateurpersonnalise',),
        ),
        migrations.CreateModel(
            name='DonateurEntreprise',
            fields=[
                ('donateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donateur')),
                ('numero_fiscal', models.CharField(max_length=100)),
                ('statut_juridique', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
            ],
            options={
                'verbose_name': 'Donateur Entreprise',
                'verbose_name_plural': 'Donateurs Entreprises',
                'db_table': 'donateur_entreprise',
            },
            bases=('donations.donateur',),
        ),
        migrations.CreateModel(
            name='DonateurOrganisation',
            fields=[
                ('donateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donateur')),
                ('numero_MATD', models.CharField(max_length=100)),
                ('statut_juridique', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
            ],
            options={
                'verbose_name': 'Donateur Organisation',
                'verbose_name_plural': 'Donateurs Organisations',
                'db_table': 'donateur_organisation',
            },
            bases=('donations.donateur',),
        ),
        migrations.CreateModel(
            name='DonateurPersonne',
            fields=[
                ('donateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donateur')),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10)),
                ('date_naissance', models.DateField()),
            ],
            options={
                'verbose_name': 'Donateur Personne',
                'verbose_name_plural': 'Donateurs Personnes',
                'db_table': 'donateur_personne',
            },
            bases=('donations.donateur',),
        ),
    ]
