# Generated by Django 5.0.3 on 2024-05-11 18:15

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonateurEntreprise',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_verification', models.BooleanField(default=False)),
                ('date_creation_compte', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('bibliographie', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_personnel', models.BooleanField(default=False)),
                ('est_superutilisateur', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_donateur', models.CharField(choices=[('individu', 'Individu'), ('entreprise', 'Entreprise'), ('organisation', 'Organisation')], max_length=100)),
                ('preferences_besoins', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=100)),
                ('numero_fiscal', models.CharField(max_length=100)),
                ('statut_juridique', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
            ],
            options={
                'verbose_name': 'Donateur Entreprise',
                'verbose_name_plural': 'Donateurs Entreprise',
            },
            managers=[
                ('objets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DonateurOrganisation',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_verification', models.BooleanField(default=False)),
                ('date_creation_compte', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('bibliographie', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_personnel', models.BooleanField(default=False)),
                ('est_superutilisateur', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_donateur', models.CharField(choices=[('individu', 'Individu'), ('entreprise', 'Entreprise'), ('organisation', 'Organisation')], max_length=100)),
                ('preferences_besoins', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=100)),
                ('numero_fiscal', models.CharField(max_length=100)),
                ('statut_juridique', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
            ],
            options={
                'verbose_name': 'Donateur Organisation',
                'verbose_name_plural': 'Donateurs Organisation',
            },
            managers=[
                ('objets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DonateurPersonne',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_verification', models.BooleanField(default=False)),
                ('date_creation_compte', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('bibliographie', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_personnel', models.BooleanField(default=False)),
                ('est_superutilisateur', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_donateur', models.CharField(choices=[('individu', 'Individu'), ('entreprise', 'Entreprise'), ('organisation', 'Organisation')], max_length=100)),
                ('preferences_besoins', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10)),
                ('date_naissance', models.DateField()),
            ],
            options={
                'verbose_name': 'Donateur Personne',
                'verbose_name_plural': 'Donateurs Personnes',
            },
            managers=[
                ('objets', django.db.models.manager.Manager()),
            ],
        ),
    ]
