# Generated by Django 5.0.4 on 2024-05-30 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Necessiteux', '0001_initial'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('financier', 'Financier'), ('materiel', 'Matériel')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='Necessiteux.besoin')),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donateur')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donation',
            },
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('donateurpersonne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donateurpersonne')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'db_table': 'visiteur',
            },
            bases=('donations.donateurpersonne',),
        ),
        migrations.CreateModel(
            name='DonationMaterielle',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donation')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('statut', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('categorie', models.CharField(choices=[('nourriture', 'Nourriture'), ('vetement', 'Vêtement'), ('equipement', 'Équipement'), ('autre', 'Autre')], max_length=100)),
                ('quantite', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Donation Matérielle',
                'verbose_name_plural': 'Donations Matérielles',
                'db_table': 'donation_materielle',
            },
            bases=('donations.donation',),
        ),
    ]
