# Generated by Django 5.0.3 on 2024-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateurentreprise',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='donateurorganisation',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='donateurpersonne',
            name='nom',
        ),
        migrations.AlterField(
            model_name='donateurentreprise',
            name='preferences_besoins',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='donateurentreprise',
            name='statut',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donateurorganisation',
            name='preferences_besoins',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='donateurorganisation',
            name='statut',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donateurpersonne',
            name='preferences_besoins',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='donateurpersonne',
            name='statut',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
