# Generated by Django 5.0.3 on 2024-05-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_donateurentreprise_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateurentreprise',
            name='preferences_besoins',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donateurentreprise',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donateurorganisation',
            name='preferences_besoins',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donateurorganisation',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donateurpersonne',
            name='preferences_besoins',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donateurpersonne',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
