# Generated by Django 5.0.3 on 2024-05-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0002_agentcollecte'),
        ('donations', '0002_donation_donationmaterielle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmaterielle',
            name='agent_collecte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_materielles', to='benevole.agentcollecte'),
        ),
    ]
