# Generated by Django 5.0.4 on 2024-05-17 17:13

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donateurentreprise_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateurpersonne',
            name='type_donateur',
        ),
        migrations.AlterField(
            model_name='donateurentreprise',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='donateurorganisation',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='donateurpersonne',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
