# Generated by Django 5.0.3 on 2024-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donationmaterielle_agent_collecte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmaterielle',
            name='statut',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
