# Generated by Django 5.0.3 on 2024-05-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_donation_donateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('donateurpersonne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donateurpersonne')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'db_table': 'visiteur',
            },
            bases=('donations.donateurpersonne',),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donateur'),
        ),
    ]
