"""
Django settings for main_dans_la_main project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e!n24u-v$v_bq&=v(+m0yc$_&3+0m320*js&-@vb%8e&-t((*('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    # 'admin_interface',
    # 'colorfield',
    'communs',
    'comptes',
    'donations',
    'website_part',
    'Necessiteux',
    'benevole',
]
X_FRAME_OPTIONS='SAMEORIGIN'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main_dans_la_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main_dans_la_main.wsgi.application'

AUTH_USER_MODEL = 'comptes.UtilisateurPersonnalise'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'main_dans_la_main',
        'HOST':'127.0.0.1',
        'USER':'root',
        'PASSWORD':'',
        'PORT':3306
    } 
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main_dans_la_main/static')    
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

'''
# Role dans l'app
PERSONNE_DONATEUR = "PersonneDonateur"
ENTREPRISE_DONATEUR="EntrepriseDonateur"
PERSONNE_NECESSITEUX="PersonneNecessiteux"
ORGANISATION_NECESSITEUX="OrganisationNecessiteux"
BENEVOLE="Benevole"
'''
# Types des utilisateurs
PERSONNE = 'personne'
ORGANISATION = 'organisation'
ENTREPRISE = 'entreprise'

# Rôles des utilisateurs
DONATEUR = 'donateur'
NECESSITEUX = 'necessiteux'
BENEVOLE = 'benevole'
AGENT_COLLECTE = 'agent_collecte'

# Types de formulaires d'envoi de besoin
BESOIN_FINANCIER = 'financier'
BESOIN_MATERIEL = 'materiel'
BESOIN_BENEVOLAT = 'benevolat'

# Les status des besoins

STATUT_BESOIN_EN_COURS = 'en cours'
STATUT_BESOIN_EN_ATTENTE = 'en attente'
STATUT_BESOIN_REJETE = 'rejete'
STATUT_BESOIN_TRAITE = 'traite'

# Configuration du serveur SMTP

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'baxel335@gmail.com'
EMAIL_HOST_PASSWORD = 'ddpjimggszujwrls'
DEFAULT_TO_EMAIL = ['baxel335@gmail.com', 'syllaingenieurinformaticien@gmail.com']
