# Generated by Django 5.0.3 on 2024-05-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='nom',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='benevole',
            name='nom',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='domaines_de_competences',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
