# Generated by Django 5.0.4 on 2024-05-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_utilisateurpersonnalise_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurpersonnalise',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
    ]
