# Generated by Django 5.0.4 on 2024-05-30 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCollecte',
            fields=[
                ('utilisateurpersonnalise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('piece_identite', models.FileField(upload_to='pieces_identite/')),
                ('localisation_geographique', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agent de Collecte',
                'verbose_name_plural': 'Agents de Collecte',
                'db_table': 'agent_collecte',
            },
            bases=('comptes.utilisateurpersonnalise',),
        ),
    ]
