# Generated by Django 5.0.3 on 2024-05-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0002_agentcollecte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'db_table': 'visiteur',
            },
        ),
    ]
